# Generated by Django 3.0 on 2019-12-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dept_no',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='emp_no',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
