# Generated by Django 3.0 on 2019-12-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_auto_20191205_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='title',
            field=models.CharField(choices=[(0, 'Staff'), (1, 'Senior staff'), (2, 'Assistant Engineer'), (3, 'Engineer'), (4, 'Senior Engineer'), (5, 'Technique Lead'), (6, 'Manger')], max_length=50),
        ),
    ]
